name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm run build

      - name: Upload sentry-client-desktop artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-sentry-client-desktop-${{ matrix.os }}
          path: apps/sentry-client-desktop/release

      - name: zip cli artifacts
        run: |
          cd apps/cli/release
          zip sentry-node-cli-macos.zip sentry-node-cli-macos
          zip sentry-node-cli-linux.zip sentry-node-cli-linux
          zip sentry-node-cli-windows.zip sentry-node-cli-win.exe
        if: matrix.os == 'ubuntu-latest'

      - name: Upload cli artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-cli-${{ matrix.os }}
          path: apps/cli/release

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-sentry-client-desktop-macos-latest/sentry-client-macos.dmg
            release-sentry-client-desktop-ubuntu-latest/sentry-client-linux.AppImage
            release-sentry-client-desktop-windows-latest/sentry-client-windows.exe
            release-cli-ubuntu-latest/sentry-node-cli-macos.zip
            release-cli-ubuntu-latest/sentry-node-cli-linux.zip
            release-cli-ubuntu-latest/sentry-node-cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}