name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo
        run: pnpm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: apps/vanguard-client-desktop/release/0.1.0

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}